version: 1.1.{build}-beta.1
image: Visual Studio 2019

configuration: Release

init:
- ps: Update-AppveyorBuild -Version "$env:appveyor_build_version+sha.$($env:appveyor_repo_commit.substring(0,7))"

nuget:
  disable_publish_on_pr: true
  
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '1.0.{build}.0'
  file_version: '1.0.{build}.0'
  informational_version: '{version}'

matrix:
  fast_finish: true # fail fast!

clone_depth: 3  

pull_requests:
  do_not_increment_build_number: true

before_build:
  - cmd: dotnet restore DotJEM.Diagnostic\DotJEM.Diagnostic\DotJEM.Diagnostic.csproj # Restores .NET Standard
  - cmd: nuget restore DotJEM.Diagnostic\DotJEM.Diagnostic.sln # Restores .NET Framework (For Test Project)

build:
  project: DotJEM.Diagnostic\DotJEM.Diagnostic.sln
  publish_nuget: true
  publish_nuget_symbols: true

test:
  assemblies:
    - '**\*.test.dll'

on_success:
- curl -s -o copilot https://copilot.blackducksoftware.com/ci/appveyor/scripts/upload
- bash copilot

deploy:
  provider: NuGet
  api_key:
    secure: ahs8uNUo4+SV91Fury7y5vlrMNkyxo7d0U+cqRMQIFtAXkqL4ZCW4BAtvaYcWaoh
  skip_symbols: false
  on:
    branch: master 
